version: '3'

networks:
  gear:

services:
  db:
    environment:
      MYSQL_DATABASE: [database]
      MYSQL_USER: [user]
      MYSQL_PASSWORD: [user_pw]
      MYSQL_ROOT_PASSWORD: [root_pw]
    image: mysql:8.0.29-oracle  # for arm64v8 architecture
    networks:
      - gear
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    image: umgear
    networks:
      - gear
    ports:
      - "8080:80"
    restart: on-failure
    volumes:
      - ..:/opt/gEAR/

  queue:
    image: rabbitmq:3.11.4
    networks:
      - gear
    ports:
      - "5672:5672"
    restart: always

# TODO: Make a consumer
