version: '3'

networks:
  gear:

services:
  db:
    environment:
      MYSQL_DATABASE: [db]
      MYSQL_USER: [user]
      MYSQL_PASSWORD: [user_pw]
      MYSQL_ROOT_PASSWORD: [root_pw]
    image: mysql:5.7
    networks:
      - gear
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    image: umgear
    networks:
      - gear
    ports:
      - "8080:80"
    restart: on-failure
    volumes:
      - ..:/opt/gEAR/

